# Generated by Django 5.1.4 on 2025-01-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dataofbirth', models.DateField()),
                ('phonenumber', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
